<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>RegulatedAIWorkflow.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RegulatedAIWorkflow.Core\RegulatedAIWorkflow.Core.csproj" />
    <ProjectReference Include="..\RegulatedAIWorkflow.Infrastructure\RegulatedAIWorkflow.Infrastructure.csproj" />
  </ItemGroup>
</Project>
